name: deploy #[optional] The name of the workflow as it will appear in the Actions tab of the GitHub repository.

on:
  pull_request: # Specifies the trigger for this workflow. if no detail, maybe use [push]?
    types: 
      - closed
    branches:
      - main  # default branch

jobs: # groups together all jobs
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # use what action
      - name: Use Node.js 14.x    # give use a name
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Cache NPM dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: npm install
      - name: Clean
        run: npm run clean
      - name: Build
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          user_name: chuanchuan
          user_email: mailforshen@gmail.com